### ISSUE TITLE
Add support for `.projectionist.json`

### ISSUE THREAD

**Issue by hauleth** [igemnace/vim-makery#5]
I think it would be good idea to provide support for vim-projectionist.

**Comment by igemnace** [comment]
As in, we get `make` and `dispatch` from `.projections.json`? That'd be nice to have.

I think, in its current form, Makery won't be able to handle buffer-specific `:Makery` subcommands. Solving #3 will pave the way for this naturally, I'd bet.

**Comment by hauleth** [comment]
According to projectionist documentation you can use `projectionist#query()`:

```
You can call *projectionist#query()* to retrieve an
array of pairs of project roots and values for a given key.  Since typically
you only care about the first (most precisely targeted) value, the following
pattern may prove useful:
>
    autocmd User ProjectionistActivate call s:activate()

    function! s:activate() abort
      for [root, value] in projectionist#query('wrap')
        let &l:textwidth = value
        break
      endfor
    endfunction
<
```

**Comment by igemnace** [comment]
Ah, that makes things much easier. Will just have to be reliant on projectionist. I can work on a patch later this week. PRs welcome, of course.
