### ISSUE TITLE
[Question] Support for the "current file" variable

### ISSUE THREAD

**Issue by last5bits** [igemnace/vim-makery#9]
I want to run a linter for the current file based on something like the following:

```json
{
  "lint": {"makeprg": "clang-tidy %"}
}
```

Currently, the percent sign is not recognized correctly. Is there something like that implemented? Thanks.

**Comment by igemnace** [comment]
I did some testing myself.

1. Doing `:set makeprg=cat\ %` then `:make` prints the current file to the screen, as expected.

2. Placing the following:
```
{
    "cat": {
        "makeprg": "cat %"
    }
}
```
into `.makery.json` then doing `:Mcat` without a user-defined `:Make` command also does the right thing.

3. Interestingly, with a user-defined `:Make` command (which I set to use AsyncRun, with `:command! -bang -nargs=* -complete=file Make AsyncRun -program=make @ <args>`), the above `.makery.json` config fails.

4. With the same user-defined `:Make` command, doing `:set makeprg=cat\ %` then `:Make` also fails.

---

Makery.vim does its best to pass on settings directly to the relevant Vim mechanism; there is no parsing of the arguments. It's up to `:make` (or a user-defined `:Make`, as described in the docs) to interpret the arguments properly.

In my case, it appears that % in `makeprg` fails to be recognized properly by AsyncRun. Could you check your setup, are you providing a `:Make` command for makery.vim to use?

**Comment by last5bits** [comment]
@igemnace Thanks for your response. Indeed, I have `command! -nargs=* Make AsyncRun -program=make <args>` in my vimrc. Do you believe this issue should be reported to the AsyncRun devs instead?

**Comment by igemnace** [comment]
I believe so, thanks! Closing this, but feel free to open in light of new info.

In the meantime, you can make use of a `makeprg` of `clang-tidy` and do `:Mlint %` instead, since AsyncRun recognizes % in args properly.
